Initial feature
vocdoni/explorer pull request #1
Opened 2024-05-31 10:44 UTC by selankon

- [x] Copy from chakra template (removing unused packs, adding prettier, configuring i18n...)
- [x] Create a basic home page with a simple react query 
- [x] Add first translations
- [x] Clone landing page of actual explorer

2024-06-04 10:37 UTC, elboletaire requested changes
Looking good so far. Just a recommendation: try to create the components always extending from a chakra components, and spreading its props (I actually add an example with the copy button). This way you'll give a lot more flexibility to all components (and it will allow to make slight style changes when placing these components in other places of the website).

2024-06-04 10:37 UTC, elboletaire commented on src/Layout.tsx
I'd move this to `src/Layout/Default.tsx`, because we're probably going to have more layouts.

I leave it up to you if you want to have `src/Layout` and `src/components/Layout` (the second one for components linked to the layout, but not for layouts themselves).

2024-06-04 10:37 UTC, elboletaire commented on src/components/CopyBtn.tsx
> +    e.target.focus()
There should be no need for anything of this.

2024-06-04 10:37 UTC, elboletaire commented on src/components/CopyBtn.tsx
> +export const CopyButton = ({ toCopy, text, size, color = 'inherit' }: ICopyButton) => {
You called it CopyButton, but you're not using Button at all. Personally I would have done something like:

~~~ts
type ICopyButton = ButtonProps & {
  toCopy: string
}

export const CopyButton = ({toCopy, size, color = 'inherit', ...rest} : ICopyButton) => {
  // all the logic and stuff required
  return <Button {...rest} />
}
~~~
> Edit: note I've removed most props from ICopyButton, because they already exist on ButtonProps

Then this could be used like:

~~~ts
<CopyButton toCopy='Whatever to be copied'>The text of the copy button</CopyButton>
~~~

Note that, because I'm spreading the button props, we cana specify whatever to this button later, like color, or any other chaakra prop:

~~~ts
<CopyButton toCopy='Whatever to be copied' colorScheme='purple'>The text of the copy button</CopyButton>
~~~

2024-06-04 10:37 UTC, elboletaire commented on src/router/index.tsx
> +    createRoutesFromElements(
Let's avoid using `createRoutesFromElements`. Ask GPT to convert it to simply be an object, like we do in our other projects like ui-scaffold or vote-frame (or voting-page).

2024-06-04 11:08 UTC, selankon commented on src/Layout.tsx
9e09700

2024-06-04 11:09 UTC, selankon commented on src/components/CopyBtn.tsx
> +    e.target.focus()
Copied from old explorer, deleting it

2024-06-04 11:34 UTC, selankon commented on src/components/CopyBtn.tsx
> +export const CopyButton = ({ toCopy, text, size, color = 'inherit' }: ICopyButton) => {
5ac9a4f

2024-06-04 11:35 UTC, selankon commented on src/components/CopyBtn.tsx
> +    e.target.focus()
5ac9a4f

2024-06-04 11:58 UTC, selankon commented on src/router/index.tsx
> +    createRoutesFromElements(
7fa0c3b

2024-06-05 08:32 UTC, elboletaire approved these changes

2024-06-05 08:33 UTC, merged