Improve organization page info
vocdoni/explorer pull request #67
Opened 2024-07-19 08:34 UTC by selankon

Fixes some of https://github.com/vocdoni/explorer/issues/65

- [x] Us lazy loading tab system
- [x] Show more details info (balance, nonce...)
- [ ] Show total number of transactions
- [] Show acocunt Transfers
- [] Show acocunt fees

2024-07-23 15:37 UTC, elboletaire requested changes

2024-07-23 15:37 UTC, elboletaire commented on src/components/Organizations/Details/Elections.tsx
> +      })}
It would be cleaner to use .filter().map rather than filtering in the map itself, which is a bit weird.

2024-07-23 15:37 UTC, elboletaire commented on src/components/Organizations/Details/Fees.tsx
> +              {/*})}*/}
Remove this, or in case you're planning to continue it, move it to a component but do not import such component.

2024-07-23 15:37 UTC, elboletaire commented on src/components/Organizations/Detail.tsx
> +            </Trans>
Can we show these counts as [rounded tags](https://v2.chakra-ui.com/docs/components/tag)?

2024-07-23 15:38 UTC, elboletaire commented
After marking the review as ready I realized the pagination in fees does not work very well, but I guess that's related to the other pagination problems, right?

2024-07-24 06:55 UTC, selankon commented on src/components/Organizations/Details/Transfers.tsx
> +                          // todo: implement go to tx by its hash
This todo can be fixed when https://github.com/vocdoni/explorer/pull/58 is merged

2024-07-24 07:06 UTC, selankon commented on src/components/Organizations/Details/Elections.tsx
> +      })}
e04a948

2024-07-24 07:07 UTC, selankon commented on src/components/Organizations/Details/Fees.tsx
> +              {/*})}*/}
uuups b3a43b4

2024-07-24 07:33 UTC, selankon commented on src/components/Organizations/Detail.tsx
> +            </Trans>
2dadbb8

2024-07-24 07:49 UTC, elboletaire approved these changes

2024-07-24 07:49 UTC, merged