Implement new stats/home page
vocdoni/explorer pull request #82
Opened 2024-07-31 09:51 UTC by selankon

Fixes https://github.com/vocdoni/explorer/issues/77

Needs https://github.com/vocdoni/vocdoni-sdk/issues/403

2024-08-09 13:40 UTC, elboletaire requested changes
Without having checked the code much, some friendly reminders for when we're back of holidays:

- The tokens component takes too long to load, and there are no pending calls so it's probably something in the implementation
- We cannot publish that right column this empty... we should get the stats back to the right side, and maybe even put the tokens info inside the blockchain card
- @jpaulet said the `i` modal is not very intuitive, maybe he wants to propose something for that

2024-08-19 08:53 UTC, selankon commented
> Without having checked the code much, some friendly reminders for when we're back of holidays:
> 
>     * The tokens component takes too long to load, and there are no pending calls so it's probably something in the implementation
> 
>     * We cannot publish that right column this empty... we should get the stats back to the right side, and maybe even put the tokens info inside the blockchain card
> 
>     * @jpaulet said the `i` modal is not very intuitive, maybe he wants to propose something for that

It seems that it was an error during the build so you was looking an outdated version of the stats page. 

Check it now because the tokens component have a better behavior now.

2024-08-19 11:16 UTC, elboletaire requested changes
Two minor issues, other than that LGTM

2024-08-19 11:16 UTC, elboletaire commented on src/components/Stats/ChainDetails/TxCosts.tsx
> +    // </StatsCardWrapper>
Remove commented code please

2024-08-19 11:16 UTC, elboletaire commented on src/components/Stats/ChainDetails/StatsCards.tsx
> +  useEffect(() => {
Comment please

2024-08-20 07:48 UTC, selankon commented on src/components/Stats/ChainDetails/TxCosts.tsx
> +    // </StatsCardWrapper>
d2148c0

2024-08-20 07:48 UTC, selankon commented on src/components/Stats/ChainDetails/StatsCards.tsx
> +  useEffect(() => {
d2148c0

2024-08-20 08:34 UTC, merged